routes/web.php
<?php

use App\Http\Controllers\drugsController;
use Illuminate\Support\Facades\Route;
use Illuminate\http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('client', DrugsController::class);

Route::get('dashboard', function(){
    return view('other.dashboard');
})->name('dashboard');

Route::get('customers', function(){
    return view('other.customers');
})->name('customers');

Route::get('opcoes/{opcao?}', function($opcao=null){
    return view('other.opcoes', compact(['opcao']));
})->name('opcoes');



// Route::get('/hello/{name}', function ($name) {
//     return 'Olá! Isso é Laravel! Bem vindo ' . $name . '!';
// });

// Route::get('/hello/{name?}', function ($name=null) {
//     if(isset($name))
//         return 'Olá! Isso é Laravel! Bem vindo ' . $name . '!';
//     else
//         return 'Olá! Você não digitou seu nome!';
// });

// Route::get('/regras/{name}/{n}', function ($name, $n) {
//    for ($i=0;$i<$n;$i++)
//     echo  "$name! <br>";
// })-> where('name','[A-Za-z]+')->where('n','[0-9]+');

// Route::post('/requisicoes', function (Request $request) {
//     return 'Hello POST';
// });

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;
}

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DrugsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DrugsController extends Controller
{

    private $clients = [
        ['id'=> 1, 'name'=> 'Matheus'],
        ['id'=> 2, 'name'=> 'Davi'],
        ['id'=> 3, 'name'=> 'Maria'],
        ['id'=> 4, 'name'=> 'Guilherme']
    ];

    public function __construct (){
        $clients = session('clients');
        if (!isset($clients)) 
            session(['clients' => $this->clients]);
    }

    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = session('clients');
        return view ('clients.index', ['clients'=>$clients,'titulo'=>'All Clients']); //array associativa

        //with
        // return view ('clients.index')
        //                     ->with('clients', $clients)                 
        //                     ->with('titulo', 'Clients');

                            //compact
        //return view ('clients.index', compact(['client']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $clients = session('clients');
        $id = array_key_last($clients) + 1;
        $name = $request -> name;
        $data = ['id'=> $id, 'name'=> $name];
        $clients[] = $data;
        session(['clients' => $clients]);
        return redirect()->route('client.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $clientes = session('clients');
        $index = $this->getIndex($id, $clientes);
        $client = $clientes [$index];
        return view('clients.info', compact(['client']));
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $clientes = session('clients');
        $index = $this->getIndex($id, $clientes);
        $client = $clientes [$index];
        return view('clients.edit', compact(['client']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $clientes = session('clients');
        $index = $this->getIndex($id, $clientes);
        $clientes[$index]['name'] = $request->name;
        session(['clients' => $clientes]);
        return redirect()->route('client.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $clients = session('clients');
        $index = $this->getIndex($id, $clients);
        array_splice($clients, $index, 1);
        session(['clients' => $clients]);
        return redirect()->route('client.index');
    }

    private function getIndex($id, $clients){
        $ids = array_column($clients, 'id');
        $index = array_search($id,$ids);
        return $index;
    }
    

}

resources/views/clients/create.blade.php
@extends('templates.principal')
@section('conteudo')
    <h3 class="title">New client:</h3>
    <hr>
    <form action="{{route('client.store')}}" method="POST">
        @csrf
        <input type="text" name="name" id="">
        <input type="submit" value="Cadastrar">
    </form>
@endsection

resources/views/clients/edit.blade.php
@extends('templates.principal')
@section('conteudo')
    <h3 class="title">New client:</h3>
    <hr>
    <form action="{{route('client.update', $client['id'] )}}" method="POST">
        @csrf
        @method('PUT')
        <input type="text" name="name" value="{{$client['name']}}">
        <input type="submit" value="Salvar">
    </form>
@endsection

resources/views/clients/index.blade.php
@extends('templates.principal')
@section('conteudo')
        <h1 class="title">{{$titulo}}</h1>
        <a class="subtitle" href="{{route('client.create')}}">Criar</a>
        <hr>
            @if (count($clients)>0)
                <ul >
                    @foreach ($clients as $c)
                        <li>
                            {{$c['id']}}: {{$c['name']}}
                            <a href="{{route('client.edit', $c['id'])}}">Editar</a> |
                            <a href="{{route('client.show', $c['id'])}}">Info</a> | 
                            <form action="{{route('client.destroy', $c['id'] )}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <input class="button is-small" type="submit" value="Delete">
                            </form>
                        </li>
                    @endforeach
                </ul>
                <hr>
                

                @foreach ($clients as $c)
                    
                @endforeach
            @endif
    @empty($clients)
            <h4>Não existem clientes cadastrados</h4>
    @endempty
@endsection

resources/views/clients/info.blade.php
@extends('templates.principal')
@section('conteudo')
    <h3 class="title">Client information:</h3>
    <hr>
    <p>ID: {{$client['id']}}</p>
    <p>Name: {{$client['name']}}</p><br>
    <a href="{{route('client.index')}}">Back</a>
@endsection

resources/views/other/customers.blade.php
@extends('templates.principal')
@section('conteudo')
        <h1 class="title">New client:</h1>
        <ul>
            <li>Option 1</li>
            <li>Option 2</li>
            <li>Option 3</li>
            <li>Option 4</li>
        </ul>
        <br>
        
<x-alert titulo="Alert!" tipo="info">
    <p><strong>Lorem ipsum! </strong></p>
</x-alert>

<x-alert titulo="Alert!" tipo="sucess">
    <p><strong>Lorem ipsum! </strong></p>
</x-alert>
<x-alert titulo="Alert!" tipo="primary">
    <p><strong>Lorem ipsum! </strong></p>
</x-alert>
<x-alert titulo="Alert!" tipo="link">
    <p><strong>Lorem ipsum! </strong></p>
</x-alert>
<x-alert titulo="Alert!" tipo="warning">
    <p><strong>Lorem ipsum! </strong></p>
</x-alert>

<x-alert titulo="Alert!" tipo="danger">
    <p><strong>Lorem ipsum! </strong></p>
</x-alert>

@endsection

resources/views/other/dashboard.blade.php
@extends('templates.principal')
@section('conteudo')
    <h3 class="title">New client:</h3>
        <ul>
            <li>Option 1</li>
            <li>Option 2</li>
            <li>Option 3</li>
            <li>Option 4</li>
        </ul>
<br>
   
@endsection

resources/views/other/opcoes.blade.php
@extends('templates.principal')
@section('conteudo')
    <div>
        <ul class="options">
            <li><a class="{{request()->routeIs('opcoes',1) ? 'danger selected' : ''}}" href="{{route('opcoes',1)}}">warning</a></li>
            <li><a class="{{request()->routeIs('opcoes',2)  ? 'info selected' : ''}}"    href="{{route('opcoes',2)}}">info</a></li>
            <li><a class="{{request()->routeIs('opcoes',3)  ? 'success selected' : ''}}" href="{{route('opcoes',3)}}">sucess</a></li>
            <li><a class="{{request()->routeIs('opcoes',4)  ? 'error selected' : ''}}"   href="{{route('opcoes',4)}}">error</a></li>
        </ul>
    </div>

@if (isset($opcao))

    @switch($opcao)

    @case(1)
    <x-alert titulo="Alert!" tipo="info">
        <p><strong>Lorem ipsum! </strong></p>
    </x-alert>
        @break

    @case(2)
        <x-alert titulo="Alert!" tipo="sucess">
            <p><strong>Lorem ipsum! </strong></p>
        </x-alert>
            @break

    @case(3)
    <x-alert titulo="Alert!" tipo="primary">
        <p><strong>Lorem ipsum! </strong></p>
    </x-alert>
    @break

    @case(4)
    <x-alert titulo="Alert!" tipo="link">
        <p><strong>Lorem ipsum! </strong></p>
    </x-alert>
    @break
    @default

    @endswitch
@endif
@endsection

resources/views/templates/principal.blade.php
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <title>PHP Study</title>
</head>
<body> 
    <div class="flex-container">
        <div class="flex-item-left">
            <div class="menu">
                <p class="menu-label">
                    Menu
                </p>
                <ul class="menu-list">
                    <li><a class="{{request()->routeIs('client.*') ? 'is-active' : ''}}" href="{{route('client.index')}}">Clients</a></li>
                    <li><a class="{{request()->routeIs('dashboard') ? 'is-active' : ''}}" href="{{route('dashboard')}}">Dashboard</a></li>
                    <li><a class="{{request()->routeIs('customers') ? 'is-active' : ''}}"  href="{{route('customers')}}">Customers</a></li>
                    <li><a class="{{request()->routeIs('opcoes') ? 'is-active' : ''}}"  href="{{route('opcoes')}}">Opções</a></li>
                </ul>
            </div>       
        </div>
        <div class="flex-item-right">
            <div class="">
                @yield('conteudo')
            </div>
        </div>
      </div>
            
</body>
</html>